CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    email_verified_at TIMESTAMPTZ,
    disabled_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_normalized CHECK (email = lower(trim(email)))
);
CREATE TABLE auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    provider VARCHAR(16) NOT NULL CHECK (provider IN ('LOCAL', 'GOOGLE')),
    subject VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255),
    UNIQUE (provider, subject), UNIQUE (user_id, provider),
    CHECK ((provider = 'LOCAL' AND password_hash IS NOT NULL) OR (provider = 'GOOGLE' AND password_hash IS NULL))
);
CREATE TABLE auth_sessions (
    id UUID PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ,
    CHECK (expires_at > created_at)
);
-- Session list/revocation and maximum-active-session enforcement by user.
CREATE INDEX idx_auth_sessions_active_user ON auth_sessions(user_id, created_at DESC) WHERE revoked_at IS NULL;
CREATE TABLE auth_refresh_tokens (
    id UUID PRIMARY KEY, session_id UUID NOT NULL REFERENCES auth_sessions(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ
);
CREATE INDEX idx_auth_refresh_session ON auth_refresh_tokens(session_id);
CREATE TABLE auth_account_tokens (
    id UUID PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
    purpose VARCHAR(16) NOT NULL CHECK (purpose IN ('VERIFY_EMAIL', 'RESET_PASSWORD')),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL, consumed_at TIMESTAMPTZ,
    CHECK (expires_at > created_at)
);
-- Token cooldown and invalidation by user and purpose.
CREATE INDEX idx_auth_account_tokens_user ON auth_account_tokens(user_id, purpose, created_at DESC);
